---
title: "PredmiRNA"
author: "Bo Zheng, Marius Rüve, Filip Mazug, Lukas Jansen"
date: "`r format(Sys.Date())`"
output: 
   revealjs::revealjs_presentation:
    toc: true
    theme:  league
bibliography: bibliography.bib
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Einleitung

## Micro RNA

- Kleines, **nicht codierendes** RNA Molekül, welches man in 
- In Pflanzen, Tieren oder Viren vorzufinden
- Ca. *22 Nukleotide* groß
- Lagert sich an komplementäre messenger RNA: **posttranskriptionale Regulation der Genexpression**
- Verhindert die Anlagerung an die Ribosomen: **keine Proteinbiosynthese** 
  
[@stanley]

## Motivation

- Micro RNA Bedeutung und Wichtigkeit; Medizinische Zwecke
- Daher ML als Ansatz zur vorhersage von miRNA
- Ziel: Feature Kombination, Machine Learining verstehen, Berührung mir versch. Prog.sprachen

## Machine Learning

- Anwendung von künstlicher Intelligenz
  - Möglichkeit des Lernens anhand von Testdaten
- Verschiedene Machine Learning (ML) Mathoden:
  - Supervised ML:
    - Alle Ergebnisse der Daten eines Testdatensatzes sind gegeben, basierend auf diesen lernt der Algorithmus die Ergebnisse für unbekannte Daten vorherzusagen
  - Unsupervised ML:
    - Hier sind die Ergebnisse für die Testdaten nich gegeben und der Algorithmus muss selber eine Struktur erkennen/ lernen, wodurch er neue Daten bewerten kann

# Phasen

## Phase 1 - Done

- Vorbereitung der Features
  - Inhalt/ Aussage der einzelnen Features
  - Verstehen der Berechnung
  - Planung des Outputs
  - Mögliche Tools zur Vereinfachung
- Schreiben der einzelnen Skripte für die Features

## Phase 2 - Done

- Einbindung der Skripte in den Workflow (Snakemake)
  - Testdaten --> Ergebnisse der einzelnen Features
- Visualisierung der Daten

## Phase 3 - WIP

- Java/ R/ Python Programm, welches in WEKA verschiedenen Modelle trainiert und auswertet
- Lulu hilf uns ! plz 


# RNAFold & Feature Beispiele

## RNAFold
ghgh


## Bsp1
Erklärung + Bilder

## Bsp2

## Bsp3

# Erklärung der Tools und Vorgehensweise

## GitHub
- Öffentliche einsehbare Git Repos
- Tooling mit Web GUI and Issue Tracker z. B.
- GitHub Profil als Portofolio eines Entwicklers
- Reproduktion: git clone, snakemake report, DONE!

## Snakemake
- Snakemake ist ein auf Python basierendes Workflow-Management-Tool
- Ein Workflow beinhaltet ein Satz an Regeln
- Eine Regel ist eine Beschreibung, wie aus einem Input-File ein Output-File zu erzeugen ist
- Dadurch können Ergebnisse von einem Skript an ein anderes weitergegeben werden

[@snakemake]

## WeKa

- Sammlung von ML Algorithmen für Data Mining Augaben
- Die Algorithmen können entweder direkt auf die Daten angewendet werden oder in einem Java Programm aufgrufen werden
-  Weka beinhaltet Tools zur Daten-Vorbereitung, Klassifizierung, Regression, Clustering und Visualisierung

## Python

- Intepretierte, High-Level, Allzweck-Programmiersprache
- Readability
- Genutzt für: Web development, software development, mathematics, system scripting
- Einfache Syntax ähnlich zur englischen Sprache
- Benutzt neue Linien anstelle von z.B. Semikolons

## R
- Programmiersprache und kostenlose Software Enviroment für statistische Berechnungen und Grafiken 
- Wird benutzt von Statistiker und Data Miner um statistische Software und Daten Analysen zu entwickeln

## Conda
- Problem in der Bioinformatik: Viele Tools, die von verschiedenen Libraries/anderen Tools abhängen
- Conda ist ein Packagemanager vergleichbar wie apt, aber versatiler als pip

## Vorgehensweise

## References {.allowframebreaks} 

